[cmd_duration]
format = '\[[$duration]($style)\]'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[hostname]
ssh_symbol = " "

[aws]
format = '\[[$symbol($profile )(\($region\) )(\[$duration\] )]($style)\]'
symbol = " "

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[docker_context]
format = '\[[$symbol $context]($style)\]'
symbol = " "

[helm]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
format = '\[[$symbol $context(\($namespace\))]($style)\]'
disabled = false

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "
pyenv_version_name = true
pyenv_prefix = "~"
python_binary = "python3"
detect_env_vars = ["VIRTUAL_ENV", "PYENV_VERSION"]

[lua]
disabled = true

[package]
format = '\[[$symbol$version]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol($workspace)]($style)\]'
symbol = "󱁢 "

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[os.symbols]
Arch = " "
CentOS = " "
Debian = " "
Ubuntu = " "
Unknown = " "
