# add_newline = false
# format = """
# $username\
# $hostname\
# $directory\
# $git_branch\
# $git_commit\
# $git_state\
# $git_status\
# $python\
# $character"""

# [line_break]
# disabled = true

[cmd_duration]
format = '\[[$duration]($style)\]'

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[hostname]
ssh_symbol = " "

[git_branch]
format = '\[[$symbol$branch]($style)\]'
symbol = " "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
symbol = " "
pyenv_version_name = true
pyenv_prefix = "~"
python_binary = "python3"

[lua]
disabled = true

[package]
format = '\[[$symbol$version]($style)\]'
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\]'
symbol = " "

[terraform]
format = '\[[$symbol$workspace]($style)\]'
symbol = "tf:"

[os.symbols]
Arch = " "
CentOS = " "
Debian = " "
Ubuntu = " "
Unknown = " "
