"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$golang\
$helm\
$lua\
$nodejs\
$opa\
$python\
$rust\
$terraform\
$zig\
$memory_usage\
$aws\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""

[cmd_duration]
format = '\[[$duration]($style)\]'

# [username]

[hostname]
ssh_symbol = " "

# [directory]

[kubernetes]
disabled = false
format = '\[[$symbol $context(\($namespace\))]($style)\]'

[git_branch]
symbol = " "
format = '\[[$symbol$branch]($style)\]'

# [git_commit]

# [git_state]

# [git_metrics]

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[docker_context]
symbol = " "
format = '\[[$symbol$context]($style)\]'

[package]
symbol = " "
format = '\[[$symbol$version]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

# [cmake]

# [golang]

[helm]
format = '\[[$symbol($version)]($style)\]'

[lua]
disabled = true

[nodejs]
format = '\[[$symbol($version)]($style)\]'

# [opa]

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
pyenv_version_name = true
pyenv_prefix = "~"
python_binary = "python3"
detect_env_vars = ["VIRTUAL_ENV", "PYENV_VERSION"]

[rust]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol($workspace)]($style)\]'
symbol = "󱁢 "

# [zig]

# [memory_usage]

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = " "

# [direnv]

# [env_var]

# [custom]

# [sudo]

# [cmd_duration]

# [line_break]

# [jobs]

# [time]

# [status]

# [os]

[os.symbols]
Arch = " "
CentOS = " "
Debian = " "
Ubuntu = " "
Unknown = " "

# [container]

# [shell]

[character]
disabled = false
success_symbol = '[](bold green) '
error_symbol = '[](bold red) '
